#version: '3'

services:
    db:
        image: mariadb:10.3.9
        volumes:
            - data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=manager
            - MYSQL_PASSWORD=secret
    web:
        image: wordpress:4.9.8
        depends_on:
            - db
        volumes:
            - ./target:/var/www/html
        environment:
            - WORDPRESS_DB_USER=manager
            - WORDPRESS_DB_PASSWORD=secret
            - WORDPRESS_DB_HOST=db
        ports:
            - 8080:80
    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    #     environment:
    #     - discovery.type=single-node
    #     ports:
    #     - 9200:9200
    #     - 9300:9300
    # logstash:
    #     image: docker.elastic.co/logstash/logstash:8.11.4
    #     ports:
    #     - 5000:5000
    # kibana:
    #     image: docker.elastic.co/kibana/kibana:8.11.4
    #     ports:
    #     - 5601:5601

volumes:
    data:
